In [1]:
import torch
from torch import nn

In [2]:
inputs = torch.Tensor([[[0.2,0.1,0.3],[0.5,0.1,0.1]]])
B,S,E= inputs.size()
inputs = inputs.reshape(S,B,E)
inputs.size()

torch.Size([2, 1, 3])

In [3]:
parameter_shape = inputs.size()[-2:]
gamma = nn.Parameter(torch.ones(parameter_shape))
beta= nn.Parameter(torch.zeros(parameter_shape))

In [4]:
gamma.size() , beta.size()

(torch.Size([1, 3]), torch.Size([1, 3]))

In [5]:
dims = [-(i+1) for i in range(len(parameter_shape))]

In [6]:
dims

[-1, -2]

In [7]:
mean = inputs.mean(dim=dims , keepdim=True)
mean.size()

torch.Size([2, 1, 1])

In [8]:
mean

tensor([[[0.2000]],

        [[0.2333]]])

In [9]:
var = ((inputs-mean)**2).mean(dim=dims,keepdim=True)
epsilon=1e-5
std=(var+epsilon).sqrt()
std

tensor([[[0.0817]],

        [[0.1886]]])

In [10]:
y = (inputs-mean)/std
y

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]])

In [11]:
out =gamma*y +beta

In [12]:
out

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]], grad_fn=<AddBackward0>)

In [21]:
import torch
from torch import nn
class LayerNormalization():
    def __init__(self,Parameter_shape,eps=1e-5):
        self.parameters_shape = Parameter_shape
        self.eps=eps
        self.gemma = nn.Parameter(torch.ones(parameter_shape))
        self.beta = nn.Parameter(torch.zeros(parameter_shape))
    def forward(self , input):
        dims=[-(i+1) for i in range(len(self.parameters_shape))]
        mean=inputs.mean(dim=dims,keepdim=True)
        print(f"Mean \n ({mean.size()}):\n {mean}")
        var=((inputs-mean)**2).mean(dim=dims,keepdim=True)
        std=(var+self.eps).sqrt()
        print(f"Standard Deviation \n ({std.size()}):\n {std}")
        y=(inputs-mean)/std
        print(f"y \n ({y.size()}) = \n {y}")
        out=self.gemma * y +self.beta
        print(f"out \n ({out.size()})= \n {out}")
        return out

In [22]:
batch_size=3
sentence_length=5
embedding_dim=8
inputs = torch.randn(sentence_length,batch_size,embedding_dim)
print(f"input \n ({inputs.size()}) = \n {inputs}")

input 
 (torch.Size([5, 3, 8])) = 
 tensor([[[-0.2957, -1.0162,  0.8366,  1.0397, -0.2092, -1.0388, -0.0887,
          -1.3184],
         [ 0.4750, -0.4020,  0.3287,  0.3990,  0.0811, -1.5061, -0.1285,
          -1.8140],
         [ 1.0124,  0.0941,  0.1472,  1.1925,  0.1442,  1.8944,  1.9388,
          -0.7511]],

        [[ 1.6309, -1.5147,  1.3785,  1.3171, -0.0369, -0.0606, -1.0579,
          -1.0193],
         [-0.2360, -1.4006, -0.5134, -1.1308, -0.1040, -0.6968, -1.0409,
          -0.0840],
         [-1.1480, -1.2017, -1.8017, -0.3987, -2.1523, -0.3158,  0.4949,
           0.9433]],

        [[ 1.0028,  0.6672,  1.1469, -1.2203, -0.2666,  1.2682, -0.3031,
          -0.3401],
         [ 1.0730,  0.9047, -1.3346,  0.8323, -0.8746,  0.8600,  1.9366,
          -1.4452],
         [-1.0874, -1.1360,  0.7158, -0.3034, -0.0942, -0.5340, -2.5102,
           0.1916]],

        [[ 0.0111, -1.5938, -0.6747,  1.9637, -0.2761, -1.5609, -1.2378,
           1.3630],
         [-0.4004,  0.0035, 

In [23]:
layer_norm= LayerNormalization(inputs.size()[-1:])

In [24]:
out = layer_norm.forward(inputs)

Mean 
 (torch.Size([5, 3, 1])):
 tensor([[[-0.2613],
         [-0.3209],
         [ 0.7090]],

        [[ 0.0796],
         [-0.6508],
         [-0.6975]],

        [[ 0.2444],
         [ 0.2440],
         [-0.5947]],

        [[-0.2507],
         [ 0.2940],
         [ 0.6308]],

        [[ 0.5517],
         [-0.2463],
         [ 0.3493]]])
Standard Deviation 
 (torch.Size([5, 3, 1])):
 tensor([[[0.8081],
         [0.8226],
         [0.8936]],

        [[1.1566],
         [0.4688],
         [1.0088]],

        [[0.8415],
         [1.1891],
         [0.9273]],

        [[1.2375],
         [0.9028],
         [1.0178]],

        [[1.0046],
         [1.0597],
         [0.8883]]])
y 
 (torch.Size([5, 3, 8])) = 
 tensor([[[-0.0425, -0.9342,  1.3588,  1.6101,  0.0645, -0.9621,  0.2137,
          -1.3082],
         [ 0.9675, -0.0987,  0.7896,  0.8752,  0.4886, -1.4409,  0.2338,
          -1.8152],
         [ 0.3395, -0.6882, -0.6287,  0.5410, -0.6322,  1.3265,  1.3761,
          -1.6340]],

  

AttributeError: 'LayerNormalization' object has no attribute 'gemma'