In [1]:
import torch
from torch import nn

In [2]:
inputs = torch.Tensor([[[0.2,0.1,0.3],[0.5,0.1,0.1]]])
B,S,E= inputs.size()
inputs = inputs.reshape(S,B,E)
inputs.size()

torch.Size([2, 1, 3])

In [3]:
parameter_shape = inputs.size()[-2:]
gamma = nn.Parameter(torch.ones(parameter_shape))
beta= nn.Parameter(torch.zeros(parameter_shape))

In [4]:
gamma.size() , beta.size()

(torch.Size([1, 3]), torch.Size([1, 3]))

In [5]:
dims = [-(i+1) for i in range(len(parameter_shape))]

In [6]:
dims

[-1, -2]

In [7]:
mean = inputs.mean(dim=dims , keepdim=True)
mean.size()

torch.Size([2, 1, 1])

In [8]:
mean

tensor([[[0.2000]],

        [[0.2333]]])

In [9]:
var = ((inputs-mean)**2).mean(dim=dims,keepdim=True)
epsilon=1e-5
std=(var+epsilon).sqrt()
std

tensor([[[0.0817]],

        [[0.1886]]])

In [10]:
y = (inputs-mean)/std
y

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]])

In [11]:
out =gamma*y +beta

In [12]:
out

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]], grad_fn=<AddBackward0>)

In [34]:
import torch
from torch import nn
class LayerNormalization():
    def __init__(self,Parameter_shape,eps=1e-5):
        self.parameters_shape = Parameter_shape
        self.eps=eps
        self.gamma = nn.Parameter(torch.ones(parameter_shape))
        self.beta = nn.Parameter(torch.zeros(parameter_shape))
    def forward(self , input):
        dims=[-(i+1) for i in range(len(self.parameters_shape))]
        mean=inputs.mean(dim=dims,keepdim=True)
        print(f"Mean \n ({mean.size()}):\n {mean}")
        var=((inputs-mean)**2).mean(dim=dims,keepdim=True)
        std=(var+self.eps).sqrt()
        print(f"Standard Deviation \n ({std.size()}):\n {std}")
        y=(inputs-mean)/std
        print(f"y \n ({y.size()}) = \n {y}")
        out=self.gamma*y + self.beta
        print(f"out \n ({out.size()})= \n {out}")
        return out

In [35]:
batch_size=3
sentence_length=5
embedding_dim=8
inputs = torch.randn(sentence_length,batch_size,embedding_dim)
print(f"input \n ({inputs.size()}) = \n {inputs}")

input 
 (torch.Size([5, 3, 8])) = 
 tensor([[[ 0.2164, -0.1193,  0.1176,  0.7733,  0.8647, -0.1534,  2.1180,
          -1.2633],
         [ 0.3356, -0.2730,  1.3946, -0.5316,  0.0441, -0.1141,  1.2318,
          -1.0368],
         [-0.3906,  0.5289, -1.8044, -1.1515, -0.8427,  2.1920,  0.2481,
          -0.0627]],

        [[ 0.0601, -1.2522,  1.2418,  0.2391, -0.2767,  1.2703,  0.2540,
          -0.3638],
         [-1.4634, -0.6058,  0.8128,  2.1337, -0.0897, -1.2985, -0.4164,
          -2.0279],
         [-0.3858,  0.1715, -0.5656,  1.1258, -0.1598,  1.7249, -0.1692,
          -0.7915]],

        [[ 0.3250,  0.2391, -1.1581,  0.8781, -0.1370,  0.0210, -0.2908,
           0.2522],
         [-1.5470,  1.5620,  0.6832, -1.2587, -0.5990, -0.3087,  1.7681,
          -0.0310],
         [-1.0189,  1.4612,  0.5971,  0.1533, -0.9600, -3.0635,  0.4294,
          -1.7472]],

        [[ 1.8924, -1.1453,  0.7231, -2.2260, -0.1977, -0.6423,  0.4210,
           1.7825],
         [ 1.1058, -0.1404, 